apiVersion: v1
kind: Service
metadata:
  name: {{ include "srs.name" . }}
  labels:
    app: {{ include "srs.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "srs.name" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "srs.name" . }}-nginx
  labels:
    app: {{ include "srs.name" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "srs.name" . }}
    